---
title: "'Catch' no puede aparecer fuera de una instrucción 'Try'."
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: c8e2b8f9ea5bf5165a97c5b38261a79df1e3b894
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 06/04/2020
ms.locfileid: "84403763"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>'Catch' no puede aparecer fuera de una instrucción 'Try'.
`Catch` debe aparecer dentro de un bloque de instrucciones `Try...Catch...Finally` . O bien hay una instrucción `Catch` innecesaria en su bloque `Try` , o la instrucción `Catch` aparece fuera de los límites de su bloque `Try` correspondiente.  
  
 **Identificador de error:** BC30380  
  
## <a name="to-correct-this-error"></a>Para corregir este error  
  
1. Elimine la instrucción `Catch` si es innecesaria, o colóquela en un bloque de instrucciones `Try...Catch...Finally` .  
  
## <a name="see-also"></a>Consulte también

- [Instrucción Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
