---
title: La instrucción 'Throw' no puede omitir el operando fuera de una instrucción 'Catch' o dentro de una instrucción 'Finally'
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: 05fc14b0f493b3901fda9fbdba7e0fcebae6bea5
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 09/23/2020
ms.locfileid: "91068900"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a>La instrucción 'Throw' no puede omitir el operando fuera de una instrucción 'Catch' o dentro de una instrucción 'Finally'

Las instrucciones`Throw` fuera de una instrucción `Catch` deben facilitar el nombre de un objeto de excepción.  
  
 **Id. de error:** BC30666  
  
## <a name="to-correct-this-error"></a>Para corregir este error  
  
1. Especifique el nombre de un objeto de excepción que derive de `System.Exception`.  
  
2. Reestructure el código para que la instrucción `Throw` se encuentre dentro de un bloque `Catch` .  
  
## <a name="see-also"></a>Vea también

- [Throw (Instrucción)](../language-reference/statements/throw-statement.md)
- [Instrucción Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [Controlar y generar excepciones en .NET](../../standard/exceptions/index.md)
