---
title: No se alcanzó el bloque 'Catch'; '<exception>' se controla anteriormente en la misma instrucción Try
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: 5133bfd9b4471350691407dee09feec2d3af444a
ms.sourcegitcommit: bf5c5850654187705bc94cc40ebfb62fe346ab02
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 09/23/2020
ms.locfileid: "91084559"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a>No se alcanzó el bloque 'Catch'; '\<exception>' se controla anteriormente en la misma instrucción Try

Un bloque `Catch` del código no se puede alcanzar porque se controla en un bloque `Try` precedente.  
  
De forma predeterminada, este mensaje es una advertencia. Para más información sobre cómo ocultar las advertencias o cómo tratarlas como errores, vea [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).
  
 **Identificador de error:** BC42031  
  
## <a name="to-correct-this-error"></a>Para corregir este error  
  
- Quite la instrucción redundante.  
  
## <a name="see-also"></a>Vea también

- [Cómo usar el bloque Try/Catch para detectar excepciones](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Utilizar controladores de excepciones filtradas por el usuario](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [Try... Detectar... Finally (instrucción)](../language-reference/statements/try-catch-finally-statement.md)
