---
title: System.ServiceModel.AsyncCallbackThrewException
ms.date: 03/30/2017
ms.assetid: dfc27ca7-b904-4f29-a5b6-dc702fa54a20
ms.openlocfilehash: 08bafd1bbc5b60e868d5d9ccd7898322d21cd32f
ms.sourcegitcommit: cdb295dd1db589ce5169ac9ff096f01fd0c2da9d
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 06/09/2020
ms.locfileid: "84594106"
---
# <a name="systemservicemodelasynccallbackthrewexception"></a>System.ServiceModel.AsyncCallbackThrewException
System.ServiceModel.AsyncCallbackThrewException  
  
## <a name="description"></a>Descripción  
 Una devolución de llamada asincrónica produjo una excepción.  
  
## <a name="see-also"></a>Vea también

- [Seguimiento](index.md)
- [Uso del seguimiento para solucionar problemas de su aplicación](using-tracing-to-troubleshoot-your-application.md)
- [Administración y diagnóstico](../index.md)
