---
title: 'Procedimiento Controlar una excepción mediante Try y Catch: Guía de programación de C#'
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#], try/catch blocks
- exceptions [C#], try/catch blocks
- try/catch blocks [C#]
ms.assetid: ca8e3773-980e-4767-8633-7408540e9818
ms.openlocfilehash: a07958c2738f020a831400df43f217e6e1b9e876
ms.sourcegitcommit: 87cfeb69226fef01acb17c56c86f978f4f4a13db
ms.translationtype: HT
ms.contentlocale: es-ES
ms.lasthandoff: 07/24/2020
ms.locfileid: "87165137"
---
# <a name="how-to-handle-an-exception-using-trycatch-c-programming-guide"></a><span data-ttu-id="04374-102">Procedimiento Controlar una excepción mediante Try y Catch (Guía de programación de C#)</span><span class="sxs-lookup"><span data-stu-id="04374-102">How to handle an exception using try/catch (C# Programming Guide)</span></span>
<span data-ttu-id="04374-103">El propósito de un bloque [try-catch](../../language-reference/keywords/try-catch.md) es detectar y controlar una excepción generada por código en funcionamiento.</span><span class="sxs-lookup"><span data-stu-id="04374-103">The purpose of a [try-catch](../../language-reference/keywords/try-catch.md) block is to catch and handle an exception generated by working code.</span></span> <span data-ttu-id="04374-104">Algunas excepciones se pueden controlar en un bloque `catch` y es posible resolver el problema sin que se vuelva a producir la excepción, pero la mayoría de las veces lo único que se puede hacer es asegurarse de que se produzca la excepción adecuada.</span><span class="sxs-lookup"><span data-stu-id="04374-104">Some exceptions can be handled in a `catch` block and the problem solved without the exception being re-thrown; however, more often the only thing that you can do is make sure that the appropriate exception is thrown.</span></span>  
  
## <a name="example"></a><span data-ttu-id="04374-105">Ejemplo</span><span class="sxs-lookup"><span data-stu-id="04374-105">Example</span></span>  
 <span data-ttu-id="04374-106">En este ejemplo, <xref:System.IndexOutOfRangeException> no es la excepción más adecuada. Tiene más sentido la excepción <xref:System.ArgumentOutOfRangeException> para el método, ya que el error lo provoca el argumento `index` pasado por el autor de la llamada.</span><span class="sxs-lookup"><span data-stu-id="04374-106">In this example, <xref:System.IndexOutOfRangeException> is not the most appropriate exception: <xref:System.ArgumentOutOfRangeException> makes more sense for the method because the error is caused by the `index` argument passed in by the caller.</span></span>  
  
 [!code-csharp[csProgGuideExceptions#5](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#5)]  
  
## <a name="comments"></a><span data-ttu-id="04374-107">Comentarios</span><span class="sxs-lookup"><span data-stu-id="04374-107">Comments</span></span>  
 <span data-ttu-id="04374-108">El código que produce una excepción está incluido en el bloque `try`.</span><span class="sxs-lookup"><span data-stu-id="04374-108">The code that causes an exception is enclosed in the `try` block.</span></span> <span data-ttu-id="04374-109">Se agrega una instrucción `catch` inmediatamente después para controlar `IndexOutOfRangeException`, si se produce.</span><span class="sxs-lookup"><span data-stu-id="04374-109">A `catch` statement is added immediately after to handle `IndexOutOfRangeException`, if it occurs.</span></span> <span data-ttu-id="04374-110">El bloque `catch` controla la excepción `IndexOutOfRangeException` y produce en su lugar la excepción `ArgumentOutOfRangeException`, más adecuada.</span><span class="sxs-lookup"><span data-stu-id="04374-110">The `catch` block handles the `IndexOutOfRangeException` and throws the more appropriate `ArgumentOutOfRangeException` exception instead.</span></span> <span data-ttu-id="04374-111">Para proporcionar al autor de la llamada tanta información como sea posible, considere la posibilidad de especificar la excepción original como <xref:System.Exception.InnerException%2A> de la nueva excepción.</span><span class="sxs-lookup"><span data-stu-id="04374-111">In order to provide the caller with as much information as possible, consider specifying the original exception as the <xref:System.Exception.InnerException%2A> of the new exception.</span></span> <span data-ttu-id="04374-112">Dado que la propiedad <xref:System.Exception.InnerException%2A> es [read-only](../../properties.md#read-only), debe asignarla en el constructor de la nueva excepción.</span><span class="sxs-lookup"><span data-stu-id="04374-112">Because the <xref:System.Exception.InnerException%2A> property is [read-only](../../properties.md#read-only), you must assign it in the constructor of the new exception.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="04374-113">Vea también</span><span class="sxs-lookup"><span data-stu-id="04374-113">See also</span></span>

- [<span data-ttu-id="04374-114">Guía de programación de C#</span><span class="sxs-lookup"><span data-stu-id="04374-114">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="04374-115">Excepciones y control de excepciones</span><span class="sxs-lookup"><span data-stu-id="04374-115">Exceptions and Exception Handling</span></span>](./index.md)
- [<span data-ttu-id="04374-116">Control de excepciones</span><span class="sxs-lookup"><span data-stu-id="04374-116">Exception Handling</span></span>](./exception-handling.md)
