---
title: 'Procedimiento Controlar una excepción mediante Try y Catch: Guía de programación de C#'
description: Aprenda a controlar una excepción mediante un bloque try-catch. Vea un ejemplo de código y examine los recursos adicionales disponibles.
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#], try/catch blocks
- exceptions [C#], try/catch blocks
- try/catch blocks [C#]
ms.assetid: ca8e3773-980e-4767-8633-7408540e9818
ms.openlocfilehash: 357aebe042bc5b6e761b3c1bad258021441de22c
ms.sourcegitcommit: 6f58a5f75ceeb936f8ee5b786e9adb81a9a3bee9
ms.translationtype: HT
ms.contentlocale: es-ES
ms.lasthandoff: 07/28/2020
ms.locfileid: "87302001"
---
# <a name="how-to-handle-an-exception-using-trycatch-c-programming-guide"></a><span data-ttu-id="ba639-104">Procedimiento Controlar una excepción mediante Try y Catch (Guía de programación de C#)</span><span class="sxs-lookup"><span data-stu-id="ba639-104">How to handle an exception using try/catch (C# Programming Guide)</span></span>
<span data-ttu-id="ba639-105">El propósito de un bloque [try-catch](../../language-reference/keywords/try-catch.md) es detectar y controlar una excepción generada por código en funcionamiento.</span><span class="sxs-lookup"><span data-stu-id="ba639-105">The purpose of a [try-catch](../../language-reference/keywords/try-catch.md) block is to catch and handle an exception generated by working code.</span></span> <span data-ttu-id="ba639-106">Algunas excepciones se pueden controlar en un bloque `catch` y es posible resolver el problema sin que se vuelva a producir la excepción, pero la mayoría de las veces lo único que se puede hacer es asegurarse de que se produzca la excepción adecuada.</span><span class="sxs-lookup"><span data-stu-id="ba639-106">Some exceptions can be handled in a `catch` block and the problem solved without the exception being re-thrown; however, more often the only thing that you can do is make sure that the appropriate exception is thrown.</span></span>  
  
## <a name="example"></a><span data-ttu-id="ba639-107">Ejemplo</span><span class="sxs-lookup"><span data-stu-id="ba639-107">Example</span></span>  
 <span data-ttu-id="ba639-108">En este ejemplo, <xref:System.IndexOutOfRangeException> no es la excepción más adecuada. Tiene más sentido la excepción <xref:System.ArgumentOutOfRangeException> para el método, ya que el error lo provoca el argumento `index` pasado por el autor de la llamada.</span><span class="sxs-lookup"><span data-stu-id="ba639-108">In this example, <xref:System.IndexOutOfRangeException> is not the most appropriate exception: <xref:System.ArgumentOutOfRangeException> makes more sense for the method because the error is caused by the `index` argument passed in by the caller.</span></span>  
  
 [!code-csharp[csProgGuideExceptions#5](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#5)]  
  
## <a name="comments"></a><span data-ttu-id="ba639-109">Comentarios</span><span class="sxs-lookup"><span data-stu-id="ba639-109">Comments</span></span>  
 <span data-ttu-id="ba639-110">El código que produce una excepción está incluido en el bloque `try`.</span><span class="sxs-lookup"><span data-stu-id="ba639-110">The code that causes an exception is enclosed in the `try` block.</span></span> <span data-ttu-id="ba639-111">Se agrega una instrucción `catch` inmediatamente después para controlar `IndexOutOfRangeException`, si se produce.</span><span class="sxs-lookup"><span data-stu-id="ba639-111">A `catch` statement is added immediately after to handle `IndexOutOfRangeException`, if it occurs.</span></span> <span data-ttu-id="ba639-112">El bloque `catch` controla la excepción `IndexOutOfRangeException` y produce en su lugar la excepción `ArgumentOutOfRangeException`, más adecuada.</span><span class="sxs-lookup"><span data-stu-id="ba639-112">The `catch` block handles the `IndexOutOfRangeException` and throws the more appropriate `ArgumentOutOfRangeException` exception instead.</span></span> <span data-ttu-id="ba639-113">Para proporcionar al autor de la llamada tanta información como sea posible, considere la posibilidad de especificar la excepción original como <xref:System.Exception.InnerException%2A> de la nueva excepción.</span><span class="sxs-lookup"><span data-stu-id="ba639-113">In order to provide the caller with as much information as possible, consider specifying the original exception as the <xref:System.Exception.InnerException%2A> of the new exception.</span></span> <span data-ttu-id="ba639-114">Dado que la propiedad <xref:System.Exception.InnerException%2A> es [read-only](../../properties.md#read-only), debe asignarla en el constructor de la nueva excepción.</span><span class="sxs-lookup"><span data-stu-id="ba639-114">Because the <xref:System.Exception.InnerException%2A> property is [read-only](../../properties.md#read-only), you must assign it in the constructor of the new exception.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="ba639-115">Vea también</span><span class="sxs-lookup"><span data-stu-id="ba639-115">See also</span></span>

- [<span data-ttu-id="ba639-116">Guía de programación de C#</span><span class="sxs-lookup"><span data-stu-id="ba639-116">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="ba639-117">Excepciones y control de excepciones</span><span class="sxs-lookup"><span data-stu-id="ba639-117">Exceptions and Exception Handling</span></span>](./index.md)
- [<span data-ttu-id="ba639-118">Control de excepciones</span><span class="sxs-lookup"><span data-stu-id="ba639-118">Exception Handling</span></span>](./exception-handling.md)
